### ISSUE TITLE
Swift3 Branch - Carthage error

### ISSUE THREAD

**Issue by rhildreth** [mapbox/MapboxDirections.swift#88] opened 2016-10-30 13:20 UTC
On Swift3 branch using Cartfile

``` cartfile
github "raphaelmor/Polyline" ~> 4.0.0
github "Mapbox/MapboxDirections.swift" "swift3"
```

`carthage update --platform iOS`   

gives error:

`The sandbox is not in sync with the Podfile.lock`

**Comment by 1ec5** [comment] 2016-11-16 19:23
#100 would replace CocoaPods with Carthage for building the example application, but there must be some other reason for this error. The use of CocoaPods for the _example application_ shouldn’t prevent the _framework_ from being compatible with Carthage.

/cc @friedbunny @incanus

**Comment by Eldorado234** [comment] 2016-12-07 16:27
#102 solves this issue. A build step CocoaPods adds to the project indeed prevented building until `pod install` was called (see discussion in #100).

**Comment by friedbunny** [comment] 2016-12-07 18:01
This issue looks like a duplicate of #46 — Carthage doesn’t work in any branch _yet_. Thanks for rounding up all of the related issues, @Eldorado234.

**Closed by friedbunny** 2016-12-07 18:01 UTC
