### ISSUE TITLE
taskWithRouter causes errors

### ISSUE THREAD

**Issue by JohnBehnke** [mapbox/MapboxDirections.swift#41] opened 2016-05-04 19:43 UTC
When attempting to incorporate the Directions files into my application, the error

 ``` Cannot convert call result type '()' to expected type 'NSURLSessionDataTask?' ```

caused by 

``return router.loadJSON(JSON.self) { [weak self] (json, error) in```... in MBDirections.swift

halts compilation of the application when using the example code. I've built the example app provided and ran the tests, which all pass.

**Comment by 1ec5** [comment] 2016-05-04 19:55
There needs to be a strong reference to the MBDirections object at least until the completion handler is executed. This is how MKDirections works, although @tmcw and I have discussed rewriting the library so that MBDirections doesn’t need to stick around.

Apart from that, I’m unable to reproduce the issue you’re describing with the example code in Xcode 7.3. Can you show us the code you’re using?

**Comment by JohnBehnke** [comment] 2016-05-04 20:12
Sure. Its available here:

https://github.com/wtg/RPI_Tours_iOS/blob/master/RPI%20Tours/RPI%20Tours/SelectedTourViewController.swift

The project currently does not use the newest release of the Directions API because of the aforementioned issue. 

The calls are in the function "calculateDirections". Currently, our team is using the older version of the Directions code that used to be in this repo (release 0.3.1 I believe), so the uncommented calls (93-132) are meant for that. At the bottom of that function is a commented section of code (lines 134-146)  that contains the example code from this repo. We were using that to test when it began to fail.  

I had added the newer release with both Cocoapods and by simply adding the code to the project directly, and both ways caused the issue.

**Comment by 1ec5** [comment] 2016-05-04 22:13
Thanks, the issue appears to be caused by an undocumented dependency on my fork of RequestKit. I’ll work to get nerdishbynature/RequestKit#14 merged, but in the meantime, you can work around the issue by inserting the following line the `Mapbox-iOS-SDK` line in your Podfile:

```ruby
pod 'NBNRequestKit', :git => 'https://github.com/1ec5/RequestKit.git', :branch => 'mapbox-podspec'
```

Apologies for the inconvenience.

**Comment by JohnBehnke** [comment] 2016-05-05 01:56
Wonderful! Thank you so much!

**Closed** 2016-06-02 07:46 UTC
Labels: bug
