### ISSUE TITLE
can't reach mauverType, maneuverDirection not visible from Objective-C

### ISSUE THREAD

**Issue by greenzeal** [mapbox/MapboxDirections.swift#163] opened 2017-08-15 12:48 UTC
Dear friends, 
Using your maps and want to reach mauverType, maneuverDirection properties of the MBRouteStep but can't. Please can you suggest the best way to solve this problem?

Thanks!

**Comment by 1ec5** [comment] 2017-08-16 10:04
Duplicate of #117.

**Comment by greenzeal** [comment] 2017-08-16 10:05
dupilicate but no answer :(

**Closed by 1ec5** 2017-08-16 10:04 UTC

**Comment by 1ec5** [comment] 2017-08-16 10:13
Unfortunately, there’s no workaround of this issue other than writing some Swift code to interact with those properties. #117 contains some ideas about fixing the issue. Unfortunately this is a good example of the downside of implementing an Objective-C-compatible library in Swift. 😕
