### ISSUE TITLE
Add new ref key

### ISSUE THREAD

**Issue by bsudekum** [mapbox/MapboxDirections.swift#77] opened 2016-10-05 15:45 UTC
Example response:

```
{
    mode: "driving",
    duration: 597,
    maneuver: {
        bearing_after: 94,
        type: "new name",
        modifier: "straight",
        bearing_before: 98,
        location: [
            -122.289247,
            37.826344
        ],
        instruction: "Continue straight onto MacArthur Freeway (I 580)"
    },
    ref: "I 580",
    distance: 15717.4,
    name: "MacArthur Freeway (I 580)"
}
```

From osrm-backend changelog:

> new ref field in the RouteStep object. It contains the reference code or name of a way. Previously merged into the name property like name (ref) and are now separate fields.

/cc @1ec5

**Comment by 1ec5** [comment] 2016-10-05 16:03
Duplicate of #67.

**Closed by 1ec5** 2016-10-05 16:03 UTC
